#%RAML 1.0 NamedExample
value:
  user_id: 1
  first_name: Jasdev
  last_name: Sharma
  email: jasdev.sharma@bitsinglass.com
  phone: 9916888307
  date_of_birth: 1988-08-12
  age: 34
  gender: "male"
  user_type: "receiver"
  blood_group: "O+"
  landmark: "Opposite Park"
  address_line_1: "123 Street Sector 62"
  district: "SAS Nagar"
  place: "Mohali"
  state: "Punjab"
  pincode: 16055
  identity_card: "pan_card"
  identity_card_number: "ATLP1234"