#%RAML 1.0 NamedExample
value:
  user_id: 4
  current_landmark: Opposite Park
  current_address_line_1: 71 Street, Sector 70
  current_district: SAS Nagar
  current_place: Mohali
  current_state: Punjab
  current_postal_code: 140407
  alternate_contact_number: 9745632018
  organ_name: Liver
  status: open
