#%RAML 1.0 NamedExample
value:
  current_landmark: Opposite XYZ Building
  current_address_line_1: 71 Street, Sector 70
  current_district: Aurangabad
  current_place: Aurangabad
  current_state: Bihar
  current_postal_code: 180556
  alternate_contact_number: 9745632018
  status: open
