#%RAML 1.0 NamedExample
value:
  request_id: 1
  first_name: Yashpal
  last_name: Yadav
  email: jasdev.sharma@bitsinglass.com
  phone: 8793012456
  blood_group: "A+"
  address_line_1: "123 Street Sector 50"
  place: "Chandigarh"
  state: "Punjab"
  identity_card: "pan_card"
  identity_card_number: "JTYP7890"
  current_landmark: Opposite Park
  current_address_line_1: 71 Street, Sector 70
  current_district: SAS Nagar
  current_city: Mohali
  current_state: Punjab
  current_postal_code: 140407
  alternate_contact_number: 9745632018
  organ_name: Kidney
  status: open
