#%RAML 1.0 NamedExample
value:
  -
    hosptial_id: 1
    hospital_name: Fortis Hospital
    email: fortis123@gmail.com
    primary_phone: 9547863012
    landmark: "Opposite Park"
    address_line_1: "123 Street Sector 62"
    district: "SAS Nagar"
    place: "Mohali"
    state: "Punjab"
    pincode: 16055
    hospital_registration_number: fortis4659
  -
    hosptial_id: 2
    hospital_name: Ivy Hospital
    email: ivy.hospital@gmail.com
    primary_phone: 8874563219
    landmark: "Near PCL Chownk"
    address_line_1: "123 Street Sector 71"
    district: "SAS Nagar"
    place: "Mohali"
    state: "Punjab"
    pincode: 16055
    hospital_registration_number: ivy8895
