db:
  host: "jdbc:postgresql://ec2-44-195-132-31.compute-1.amazonaws.com:5432/d41sn4tfe7abbb?sslmode=require"
  driverClass: "org.postgresql.Driver"
  user: "vncspdzmdlxxyj"
  pass: "e40fd4982014818a369826569b68fa8700234c8438d6bf37c148d9d6dfeec501"

http:
  host: "localhost"
  port: "8081"
  
  
common:
  addressKeys: '["landmark", "address_line_1", "address_line_2", "place", "district", "state", "pincode"]'
  userKeys    : '["first_name", "last_name", "email", "date_of_birth", "gender", "blood_group", "identity_card", "user_type", "identity_card_number", "phone", "age"]'
  hospitalKeys: '["hospital_name", "email", "hospital_registration_number", "primary_phone"]'
  currentAddressKeys: '["current_landmark", "current_address_line_1", "current_address_line_2", "current_place", "current_district", "current_state", "current_pincode"]'
  
jira:
 userName: "satish.kumar@bitsinglass.com" 
 apiToken: "PsDUYAChU25Z23iY8KiG6FA8"
 baseUri: "https://satishfordemo.atlassian.net"